environment:
  nodejs_version: '20'
install:
  - ps: Install-Product node 20
  - 'npm ci'
cache:
  - 'node_modules'
  - "%APPDATA%\\npm-cache"
build: off
test_script:
  - 'node --version'
  - 'npm --version'
  - 'npm run build'
  - 'npm test'
