import js from '@eslint/js';
import prettier from 'eslint-config-prettier';
import globals from 'globals';

// One configuration for the whole toolchain. The packages arrived from three repositories,
// each with its own eslint version and rule set - eslint 5 with airbnb for the api-elements
// packages, eslint 6 for gavel, eslint 9 flat config for dredd. Keeping sixteen of those
// would mean sixteen eslint installs to maintain, so the rules that mattered to each are
// folded in here and the repository lints once.
export default [
  {
    ignores: [
      '**/node_modules/**',
      '**/build/**',
      '**/dist/**',
      '**/coverage/**',
      'docs/**',
      '**/*.ts',
      // Vendored fixtures and recorded corpora: someone else's syntax, not ours to police.
      'packages/swagger-zoo/fixtures/**',
      'packages/*/test/fixtures/**',
      'packages/*/lib/refract/**',
      // Generated by PEG.js, regenerated from the grammar rather than edited.
      'packages/apiaryb-parser/lib/apiary-blueprint-parser.js'
    ]
  },
  js.configs.recommended,
  prettier,
  {
    languageOptions: {
      ecmaVersion: 'latest',
      sourceType: 'commonjs',
      globals: { ...globals.node }
    },
    rules: {
      // A command line tool prints to the console; that is its job.
      'no-console': 'off',
      // Function hoisting is used throughout these packages.
      'no-use-before-define': ['error', { functions: false }],
      // ANSI escapes in a regex are deliberate, for stripping terminal colour.
      'no-control-regex': 'off',
      // An unused catch binding documents what is being swallowed.
      'no-unused-vars': ['error', { caughtErrors: 'none' }]
    }
  },
  {
    // dredd and dredd-transactions ship as ES modules, as does this configuration; the rest
    // of the repository is CommonJS.
    files: [
      'eslint.config.js',
      'packages/dredd/**/*.js',
      'packages/dredd-transactions/**/*.js'
    ],
    languageOptions: { sourceType: 'module' }
  },
  {
    // Hook files and helper scripts stand in for a user's own project, which is CommonJS.
    files: ['packages/dredd/test/fixtures/**/*.js'],
    languageOptions: { sourceType: 'commonjs' }
  },
  {
    files: ['**/test/**/*.js', '**/*-test.js', '**/*.test.js'],
    languageOptions: { globals: { ...globals.node, ...globals.mocha } },
    rules: {
      // A test callback's signature exposes parameters it does not always use.
      'no-unused-vars': ['error', { args: 'none', caughtErrors: 'none' }],
      // chai assertions read as expressions: expect(x).to.be.true
      'no-unused-expressions': 'off'
    }
  }
];
