name: run-docs-test

on: push

jobs:
  commitlint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - run: npm ci
      - run: npx commitlint --from HEAD~${{ github.event.pull_request.commits }} --to HEAD

  quality-checks:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 20.x
    - uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    - run: pip install -r ./docs/requirements.txt
    - run: npm ci
    - run: npm run lint
    - run: npm run docs:lint
    - run: npm run docs:test-extensions

  docs-dry-run:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 20.x
    - uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    - run: pip install -r ./docs/requirements.txt
    - run: npm ci
    - run: npm run docs:build
